language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=docs
  - TOXENV=pypy

install:
  - git config --global user.email "travisci@jasonantman.com"
  - git config --global user.name "pydnstest-travis"
  - pip install tox

script: tox

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  except:
    - /^noci-.*$/
