language: python
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py35 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py36 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=cov PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
  - git config --global user.email "travisci@jasonantman.com"
  - git config --global user.name "pydnstest-travis"
  - pip install tox
  - pip install codecov

script:
  - tox

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  except:
    - /^noci-.*$/
