language: python
sudo: false

cache: pip

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "2.7"
      env: TOXENV=docs
    - python: "2.7"
      env: TOXENV=cov

install:
  - git config --global user.email "travisci@jasonantman.com"
  - git config --global user.name "pydnstest-travis"
  - pip install tox
  - pip install codecov

script:
  - tox

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  except:
    - /^noci-.*$/
